title: Site

tabs:
  pages:
    label: Seiten
    icon: layers
    sections:
      pages:
        type: pages

  settings:
    label: Einstellungen
    icon: cog
    sections:
      fields:
        type: fields
        fields:
          footertext:
            extends: fields/markdown
            label: Kontakt Fußzeile
          instagram:
            type: url
            label: Instagram
            width: 1/3
          youtube:
            type: url
            label: Youtube
            width: 1/3
          facebook:
            type: url
            label: Facebook
            width: 1/3


  media: tabs/media
  seo: tabs/seo

